### ISSUE TITLE
題目三

### ISSUE THREAD

**Issue by User-Howard** [Joshua09009/BeginnerCode#3]
---

You are given all numbers between 1,2,…,N except one. Your task is to find the missing number.
> N in [1, 500)
難度 0.09

---

sample input 1
```in
5
2 3 1 5
```
sample output 1
```out
4
```

---

Test Case
```in

```
<details>  <summary>Test Case</summary><code>
500 <p>
383
448
160
71
26
152
394
232
416
179
331
52
491
246
193
366
43
273
384
490
363
349
129
48
262
230
30
317
128
312
409
441
454
407
189
338
70
462
355
191
257
356
362
47
120
424
410
270
61
386
75
278
171
442
85
156
178
255
239
287
373
440
137
497
261
314
91
482
431
87
237
144
182
244
318
397
336
396
88
475
238
436
34
192
243
463
99
225
476
56
399
395
158
219
447
180
65
231
170
33
339
215
9
96
105
450
354
29
12
254
126
135
310
329
305
275
367
241
467
63
24
387
388
470
77
151
81
405
265
146
183
403
22
422
327
149
272
62
39
291
211
229
217
267
315
455
487
147
302
130
432
167
213
485
73
38
249
4
408
20
311
89
468
466
198
451
206
242
35
460
283
328
177
461
164
306
365
393
25
496
188
309
127
37
319
293
250
204
15
117
322
139
41
3
216
45
92
111
423
143
258
341
107
473
169
11
458
330
247
414
153
430
154
276
165
489
103
21
175
433
391
201
200
208
271
174
113
371
345
300
155
32
274
360
94
18
220
279
297
110
398
67
6
148
54
351
49
375
252
187
253
185
136
323
0
223
333
301
390
150
10
296
303
251
342
14
346
13
307
7
78
84
374
221
361
50
133
334
435
112
36
439
86
459
358
308
248
471
445
364
379
122
289
199
121
488
98
256
378
325
106
370
294
400
437
474
157
40
97
194
438
316
359
304
16
313
417
76
478
55
380
196
132
162
282
268
131
19
385
260
298
240
227
419
27
72
64
426
348
51
263
421
269
401
484
82
284
197
486
66
210
427
42
285
465
209
266
17
290
57
173
347
495
59
292
226
472
60
344
138
119
295
212
382
142
101
321
53
108
259
381
452
392
161
288
79
326
74
428
280
340
190
159
446
469
233
205
46
343
116
141
124
195
406
83
90
69
299
350
123
95
134
235
125
483
140
104
28
457
58
418
236
335
80
353
5
202
8
412
464
337
456
477
480
218
449
324
44
176
166
402
145
264
377
376
207
228
425
100
499
168
181
281
163
277
1
368
2
434
118
234
494
444
413
332
420
492
320
31
389
114
186
245
102
23
352
415
222
479
481
429
453
172
498
109
93
286
404
411
372
224
443
369
357
214
493
115
203
184
</code></details>

**Comment by Joshua09009** [comment]
N = int(input())
X = list(map(int, input().split()))
X.sort()
a = 0
b = 1
while (X[a] == b):
    a = a + 1
    b = b + 1
print(X[a - 1] + 1)

**Comment by Joshua09009** [comment]
`N = int(input())
X = list(map(int, input().split()))
X.sort()
a = 0
b = 1
while (X[a] == b):
    a = a + 1
    b = b + 1
print(X[a - 1] + 1) `

**Comment by Joshua09009** [comment]
我是這樣寫的

**Comment by Joshua09009** [comment]
請問正確嗎

**Comment by Joshua09009** [comment]
提問：語法len代表什麼？

**Comment by Joshua09009** [comment]
提問：我本來的語法除了過於冗長以外有什麼錯誤嗎？

**Comment by User-Howard** [comment]
你試試看
```
3
23
```

**Comment by User-Howard** [comment]
你試試看
```
3
23
```
